# Generated by Django 5.2.3 on 2026-05-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_guess', models.TextField()),
                ('industry_sector', models.CharField(choices=[('clothing', 'Clothing Store'), ('accessories', 'Accessories Store'), ('crm', 'CRM Management'), ('web_dev', 'Web Development'), ('events', 'Event Planning'), ('dating', 'Dating App/Planner'), ('other', 'Other')], max_length=50)),
                ('user_city', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
