
# Generated by Django 5.2.3 on 2026-05-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navri_bazaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketfeedback',
            name='other_sector',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='marketfeedback',
            name='industry_sector',
            field=models.CharField(choices=[('clothing', 'Clothing Store'), ('accessories', 'Accessories Store'), ('crm', 'CRM Management'), ('web_dev', 'Web Development'), ('events', 'Event Planning'), ('dating', 'Dates Planner'), ('other', 'Other')], max_length=50),
        ),
    ]
